spring:
    datasource:
        url: jdbc:postgresql://database:5432/chuck
        databaseName: chuck
        serverName: chucknorrisfactsdb
        username: chuck
        password: chuck
        

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL94Dialect
        database: POSTGRESQL
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: validate
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
